name: Generate Mega Snake

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: gaerron
          gits_fetch_options: "--deepen=2000"
          snake_density: 1
          snake_size: "xxl"
          outputs: |
            assets/mega-snake.svg

      - name: Commit with LFS
        run: |
          # 必须重新配置用户（防止某些环境丢失配置）
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

          # 初始化 LFS
          git lfs install
          git lfs track "assets/*.svg"
          
          # 提交
          git add .gitattributes assets/
          git commit -m "Add 100KB mega snake [skip ci]" || exit 0
          
          # 使用 Token 推送
          git push https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
