name: Generate Mega Snake

on:
  workflow_dispatch:  # 手动触发（避免频繁跑长任务）

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 必须！

      - name: Generate 100KB+ Snake
        uses: Platane/snk@v3
        env:
          GH_TOKEN: ${{ secrets.PAT }}  # 使用高限额Token
        with:
          github_user_name: zzgs219G
          gits_fetch_options: "--deepen=2000 --unshallow"
          snake_density: 1
          snake_size: "xxl"
          snake_type: "gatsby"
          outputs: |
            assets/mega-snake.svg
            assets/mega-snake-dark.svg?palette=github-dark

      - name: Commit
        run: |
          git lfs install
          git lfs track "assets/*.svg"
          git add .gitattributes assets/
          git commit -m "Add 100KB mega snake" 
          git push origin HEAD:main
