name: Generate and Commit Snake Animation

on:
  schedule:
    - cron: '0 0 * * *' # 每天 UTC 时间 0 点运行
  workflow_dispatch: # 允许手动触发

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 需要完整的 git 历史记录

      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: zzgs219G
          outputs: |
            assets/snake-white.svg?palette=github-light
            assets/snake-dark.svg?palette=github-dark

      - name: Commit files
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add assets/*
          git commit -m "Add generated snake SVG" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
