name: Generate Long Snake

on:
  schedule:
    - cron: '0 0 * * *'  # 每天自动更新
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate 1-year snake
        uses: Platane/snk@v3
        with:
          github_user_name: zzgs219G
          gits_fetch_options: "--depth=365"
          snake_size: "large"
          outputs: |
            assets/snake.svg
            assets/snake-dark.svg?palette=github-dark

      - name: Commit
        run: |
          git config --global user.name "GitHub Actions"
          git add assets/
          git commit -m "Update year-long snake" || exit 0
          git push https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
