name: Generate Snake

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 0 点运行
  workflow_dispatch:     # 允许手动触发

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 需要完整 git 历史记录

      - name: Generate snake
        uses: Platane/snk@v3
        with:
          github_user_name: zzgs219G
          outputs: |
            assets/snake-white.svg?palette=github-light
            assets/snake-dark.svg?palette=github-dark

      - name: Commit files (SSH)
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin git@github.com:zzgs219G/tcs.git
          git add assets/*
          git commit -m "Add generated snake SVG [skip ci]" || exit 0
          git push origin HEAD:main
